[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[[constraint]]
  name = "github.com/kublr/govcloudair"
  branch = "master"
